services:
  db:
    image: postgres:latest
    container_name: postgres_labmedicine
    restart: always
    environment:
      DATABASE_HOST: db
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_DB: labmedicine
      DATABASE_URL: postgres://user:password@db:5432/labmedicine
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: labmedicine_app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://user:password@db:5432/labmedicine"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run dev

volumes:
  postgres_data:
